version: '3.9'

services:

  # postgres:
  #   image: postgres
  #   environment:
  #     - POSTGRES_HOST=localhost
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=password123
  #     - POSTGRES_DB=fastapi
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - data:/var/lib/postgresql/data

  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver
    ports:
      - "8080:8978"
    environment:
      - CB_SERVER_PORT=8080
      - CB_SERVER_NAME=dbeaver-cloud
    volumes:
      - dbeaver_data:/opt/dbeaver/conf


volumes:
  #data:
  dbeaver_data:
